### ISSUE TITLE
Licensing Clarification

### ISSUE THREAD

**Issue by nate2014jatc** [Darkhax-Minecraft/Friendly-Fire#1]
Hi there!
We'd love to use your mod(s) in our pack, but we can't find any info about the licensing of Friendly-Fire.
The CurseForge page says that it's "all rights reserved," but we would appreciate additional clarification.

**Comment by darkhax** [comment]
The GitHub page also lacks a license, so it is all rights reserved completely. Being on GitHub does not mean that the project is open source or that you have any rights with it beyond those in the GitHub TOS. Fortunately, this project being all rights reserved is unintentional, and the project was intended to be released under the LGPL 2.1 license. I will update the project with the correct license in a few moments.

**Comment by darkhax** [comment]
License info has been added.

**Comment by nate2014jatc** [comment]
Thank you very much for your help!
I've opened a few (a lot actually) other issues for other mods asking for licensing clarification, to avoid stepping in anyone's toes.
