### ISSUE TITLE
Villagers and golems

### ISSUE THREAD

**Issue by Yupoman** [Darkhax-Minecraft/Friendly-Fire#10]
Would it be possible to add an option in the configuration for villagers and golems?

It is quite common for them to get in the way in the middle of a raid. I don't want a golem to attack me or a villager to raise my prices haha.

**Comment by Darkhax** [comment]
The newest version adds an entity tag `friendlyfire:general_protection` which will allow you to protect any mob. Keep in mind that sneaking will bypass this mod. There is also a new item tag `friendlyfire:bypass_all_protection` which allows specific items to bypass the entire mod as well.
