### ISSUE TITLE
Crash between Ice and Fire (2.1.0) and Friendly Fire (4.0.1) Minecraft 1.15.2

### ISSUE THREAD

**Issue by Phantom2909** [Darkhax-Minecraft/Friendly-Fire#11]
[crash-2020-11-30_20.40.17-server.txt](https://github.com/Darkhax-Minecraft/Friendly-Fire/files/5622891/crash-2020-11-30_20.40.17-server.txt)
Well, from what I understand from the report, there were problems between the Lightning Dragon and the mod.

**Comment by Darkhax** [comment]
Thanks for reporting. I will look into this soon.

**Comment by Darkhax** [comment]
This issue should now be fixed in Friendly Fire 4.0.2
