### ISSUE TITLE
Horses

### ISSUE THREAD

**Issue by ThizGuy24** [Darkhax-Minecraft/Friendly-Fire#12]
I installed this mod, saw that it disabled friendly fire, tried it on a horse and now the horse is dead. May be something that was overseen, but I wanted to ask: can this be patched? I'm new to mods and wanted to spice up my Minecraft experience and I'm using a mod that makes horses better. Thanks!

**Comment by Darkhax** [comment]
Thanks for reporting this, it was originally a feature but it was removed during one of the porting updates unintentionally. It's now re-added.
