### ISSUE TITLE
Suggestion;

### ISSUE THREAD

**Issue by AyanCantosa** [Darkhax-Minecraft/Friendly-Fire#14]
Is it possible for you to add a feature where, we can add what mobs we want to be protected, so if you try to hurt it/another mob tries to hurt it, it won't be hurt?

**Comment by Darkhax** [comment]
The newest version adds an entity tag friendlyfire:general_protection which will allow you to protect any mob. Keep in mind that sneaking will bypass this mod. There is also a new item tag friendlyfire:bypass_all_protection which allows specific items to bypass the entire mod as well.
