### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/Friendly-Fire#15]
Can you add to the list
Villagers? It's annoying when trying to change their jobs breaking blocks and hitting them, then an iron golem kills you
And horses?

**Comment by Darkhax** [comment]
The newest version adds an entity tag `friendlyfire:general_protection` which will allow you to protect any mob. Keep in mind that sneaking will bypass this mod. There is also a new item tag `friendlyfire:bypass_all_protection` which allows specific items to bypass the entire mod as well.

Horses are protected under the "pet" option by default, only if they are tamed.
