### ISSUE TITLE
[Suggestion] Add multiplayer pet friendly-fire disabling

### ISSUE THREAD

**Issue by Reshirou** [Darkhax-Minecraft/Friendly-Fire#17]
It is actually the most annoying thing in the world when me and some friends are taking on a boss and one of us accidentally hits someone else's tamed or summoned mob, because suddenly you become prime target number 1 to that dumb little animal

Even turning PVP off on the server doesn't do anything, and V-Tweaks' function with this idea doesn't work with mods (it is bugged to make some enemies invincible)

**Comment by luni3359** [comment]
A setting to disable all incoming player damage would be nice!

**Comment by Darkhax** [comment]
FriendlyFire now has a team feature that should account for this. The vanilla team system could also probably handle this, just set their "allowFriendlyFire" option to false.
