### ISSUE TITLE
[Suggestion] Add Option For Enable/Disable Damage To Villagers And Golems

### ISSUE THREAD

**Issue by Seikikai** [Darkhax-Minecraft/Friendly-Fire#19]
It Will Be Good A Option To Disable Damage Against Villagers And Iron Golems For Those Players Who Want It.

**Comment by LordDarovit** [comment]
100%. Would be a great addition of quality of life.

**Comment by Darkhax** [comment]
Thanks for the feature request. I am currently swamped with updating stuff to newer versions so no idea when I will get around to this. If you are on a modern version of Minecraft you can implement similar protections on your own by adding these mobs to the [`friendlyfire:general_protection`](https://github.com/Darkhax-Minecraft/Friendly-Fire/blob/1.16.5/src/main/resources/data/friendlyfire/tags/entity_types/general_protection.json) entity tag.
