### ISSUE TITLE
Immortal Cats

### ISSUE THREAD

**Issue by frakier** [Darkhax-Minecraft/Friendly-Fire#2]
FriendlyFire-1.12.2-1.5.9
BabyMobs-1.12-1.5.5
Forge 14.23.5.2807

The BabyMobs version of the Cat that follows around the Minecraft Witch [not the Ender Zoo Cat] has the label "tamed" and you cannot attack it [not sure if the label matters but so far the only mob I have found that has a issue]. One of my players thought it was a joke until it got serious; He died.

Will be sharing this with BabyMobs as well.

**Comment by Darkhax** [comment]
Thanks for reporting this issue, and sorry for the long delayed response. You can circumvent the protections provided by this mod by sneaking. In 1.13.2+ I will also be adding additional checks to prevent these situations.
