### ISSUE TITLE
Crash on Forge 1.18.2

### ISSUE THREAD

**Issue by Zano1999** [Darkhax-Minecraft/Friendly-Fire#20]
Log file: https://pastebin.com/ePyEPU5m

**Comment by Darkhax** [comment]
Sorry about that, this mod requires [Bookshelf](https://www.curseforge.com/minecraft/mc-mods/bookshelf) to run and I forgot to mark it as a dependency. A fix will be out soon that makes this clearer.

**Comment by Zano1999** [comment]
Oh ok, tnx

**Comment by Darkhax** [comment]
Should be fixed in 11.0.2 now. https://github.com/Darkhax-Minecraft/Friendly-Fire/commit/393fc63a3e786ed9f071b3ab40f28054cbd76dcb

**Comment by Zano1999** [comment]
Already fixed it installing Bookshelf :)
