### ISSUE TITLE
Arrows can still hurt pets if they get past the bouncing

### ISSUE THREAD

**Issue by luni3359** [Darkhax-Minecraft/Friendly-Fire#22]
If you shoot directly above your pet it will keep bouncing on top of them for a while but eventually it'll hurt them

**Comment by luni3359** [comment]
I'm sorry, I did more testing and it seemed like it was glitching out but it turns out that the reason why the dogs got hurt after a while is because I lowered myself down with shift in creative, so the moment I touched land I entered sneaking and triggered the pet damage. 

That being it would be cool if there was a way to tag arrows so individual projectiles reacted properly (i.e. if you fire with the intent to hurt, but then the arrow hits while you're not sneaking anymore the pet doesn't get damaged, and viceversa)

**Comment by Darkhax** [comment]
Unfortunately there isn't really a good way to tag arrows like that, and allowing the player to change their mind after the arrow has been fired is more forgiving for accidental misfires.
