### ISSUE TITLE
friendlyfire:general_protection tag on villagers makes them immune to mob damage

### ISSUE THREAD

**Issue by tomtlw** [Darkhax-Minecraft/Friendly-Fire#25]
I've noticed that no villagers could die to pillagers or zombies. Note: I'm playing with Minecraft Comes Alive reborn on 1.19.2 however it seems like without mods the normal villagers don't take damage either.

That line does successfully prevent myself from dealing damage as well.

**Comment by Darkhax** [comment]
This is an intended feature, as general_protection is general. I can look into a new tag to prevent player specific damage.

**Comment by luni3359** [comment]
This also happens to baby animals attacked by wolves. They become enraged and pounce into the babies without hurting them and don't stop following them around until they grow up.

**Comment by Darkhax** [comment]
The `friendlyfire:player_protection` tag is now a feature on 1.19.2.

**Comment by Escano2045** [comment]
> 该标签现在是 1.19.2 上的一项功能。`friendlyfire:player_protection`

How can I add the [player_protection] list in version 1.16.5
