### ISSUE TITLE
[Suggestion] Disable message that says "The Wolf is protected..."

### ISSUE THREAD

**Issue by itsjillard** [Darkhax-Minecraft/Friendly-Fire#27]
There should be an option to toggle this reminder off because it is unnecessary to be reminded everytime that it is protected, or how to intentionally hit them. 

EDIT: Apart from that, great mod! works as intended

**Comment by Darkhax** [comment]
Thanks for the feedback. A new build for 1.18.2 and 1.19.2 have been released with a `displayHitWarning` config option.
