### ISSUE TITLE
Suggestion: Doing the same for Skeletons and wither Skeletons when they hit other mobs?

### ISSUE THREAD

**Issue by SirAron111** [Darkhax-Minecraft/Friendly-Fire#3]
Suggestion: Doing the same for Skeletons and wither Skeletons when they hit other mobs?
Currently Skeletons tend to hit zombies or other skeletons way to often and then they start fighting each other.
Is it possible to add a feature to make Friendly Fire prevention in the Aggressive Faction also a thing?
Mmm but maybe that’s a bit to tricky since with various mods and many target interactions this could be going also pretty wrong. Like how would summons chose targets or how do revenge targets or dummy targets work etc.
Well it was just an idea anyway.

**Comment by Darkhax** [comment]
Thanks for the feature request. It makes sense to add this feature, although I am a bit worried that there may be some weird conflicts with other mods. For example having the twilight litch soot itself, or the deflect ghast fireball advancement. I will still consider this feature, but I will need some time to test it out.

**Comment by SirAron111** [comment]
Ye I am sure it would be difficult sry about the request XD. I was just thinking that it’s kind of annoying how Skeletons always start shooting creepers and zombies ending up getting killed by them. Especially since I am using the scaling health mod that makes dmg scale up for mobs and your damage control mod. But since the scaling health only increases meele mob dmg and your damage control mod cant increase the arrow dmg from skeletons without increasing the players arrow dmg as well (same dmg source) most skeletons get rekt when they accidentally shoot a powered up zombie.

And i bet it would be hard to make it so that things like summoned Skeletons or Special mobs wouldn’t be affected or whatever. Well it was just a random idea you can forget it before it gets to troublesome or just take your time for however long it takes I can wait.

**Comment by Darkhax** [comment]
After looking into the idea a bit more I think it would cause too many issues. Making a blacklist/whitelist is possible but it just adds a lot of work to both the mod and to pack makers. It's still a good idea though.
