### ISSUE TITLE
Datapack do not work

### ISSUE THREAD

**Issue by GingleMeow** [Darkhax-Minecraft/Friendly-Fire#48]
Forge version 43.2.13
Friendly Fire version 14.0.4
Open Loader version 15.0.1

Villagers still receive damage from player.

[FriendlyFire-Configure-1.0.0.zip](https://github.com/Darkhax-Minecraft/Friendly-Fire/files/11621381/FriendlyFire-Configure-1.0.0.zip)

**Comment by Darkhax** [comment]
Are you certain your data pack is being loaded properly? This example pack works fine for me. 
[FriendlyFire-Example-Pack.zip](https://github.com/Darkhax-Minecraft/Friendly-Fire/files/11621960/FriendlyFire-Example-Pack.zip)

**Comment by GingleMeow** [comment]
> Are you certain your data pack is being loaded properly? This example pack works fine for me. [FriendlyFire-Example-Pack.zip](https://github.com/Darkhax-Minecraft/Friendly-Fire/files/11621960/FriendlyFire-Example-Pack.zip)

Yes, it's loaded correctly, but don't work.

**Comment by Darkhax** [comment]
Did you try with the example pack? If the pack I gave you does not work then the pack has not loaded correctly or one of the mods is interfering. One possible explanation is that a mod is replacing villagers with their own villagers so the ID is not the same.

**Comment by GingleMeow** [comment]
I create a new pack include only Friendly Fire and Open Loader, and your pack works. But my original pack isn't. Maybe you are right, but I don't find the mod yet.
