### ISSUE TITLE
Support for 1.20.1

### ISSUE THREAD

**Issue by ST-DDT** [Darkhax-Minecraft/Friendly-Fire#49]
> Mod 'FriendlyFire' (friendlyfire) 17.0.1 requires version 1.20 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!

Could you please update this mod to 1.20.1?

Thanks for this helpful mod. ❤️

**Comment by Darkhax** [comment]
Sorry, I've been in the process of moving so updates have been stuck at 1.20 for a bit. Updates for 1.20.1 will come soon.
