### ISSUE TITLE
Incompatibility with Iron's Spells 'n Spellbooks

### ISSUE THREAD

**Issue by DankestO** [Darkhax-Minecraft/Friendly-Fire#52]
"Iron's spell" spells can deal damage to entities that theoretically should not take damage. Such as fireballs or other types of damage including some that are applied to the ground.

It makes sense (maybe(?) but the strange thing is with area healing spells they only work for entities that are not pets, villagers and golems receive magic damage but can also receive healing.

Pets for some reason not only receive magical damage, but also block the healing that is applied to them.

I would really appreciate it if you could do something with this and block the magic damage or at least enable healing for the pets.

(Here I use healing circle, it looks like the snow golem receives healing (green numbers) but my mule does not.)
![image](https://github.com/Darkhax-Minecraft/Friendly-Fire/assets/126206944/7774d8d1-bcbb-458f-a41b-63d6aad7c97a)

Thank you for your time and for this great mod :)

**Comment by Darkhax** [comment]
Hello, I tried to recreate this issue on 1.19.2 using the latest version of both mods and everything seems to be working as intended. From what you've described it sounds like Iron's Spells may have some bugs on older versions or you have another mod installed that is causing issues.

**Comment by DankestO** [comment]
I went to try again and better, yes, you are right, the problem seems to be with Iron itself, for some reason it does not detect the pets of other mods. Sorry for the mistake.<

edit: Checking a little more inside the irons file there are tags to label the entities you can heal, it looks like that will solve my problem.
