### ISSUE TITLE
Have Friendly Fire Protection apply to Teams

### ISSUE THREAD

**Issue by PacoDaPea** [Darkhax-Minecraft/Friendly-Fire#53]
Pretty self-explanatory. While the game already has an option to disable friendly fire in teams via commands, it only applies to players and could still harm and kill mobs in the same team and vice versa.

**Comment by solaluset** [comment]
Exactly what I did in #50! It's a pity that it didn't get accepted yet.

**Comment by Darkhax** [comment]
This has been added for 1.20.4. By default team members will not be able to hurt each other or their pets. I am not planning to backport this feature at this time.
