### ISSUE TITLE
[Suggestion] Add player friend/foe-list

### ISSUE THREAD

**Issue by ST-DDT** [Darkhax-Minecraft/Friendly-Fire#56]
It would be nice, if the friendly fire feature would also apply to players on a friend/foe-list.

Some mods add sweeping weapons, which makes it hard to fight multiple mobs or bosses close to other players.
If this mod could prevent hitting our own friends that would be awesome.

If possible this should come with 3 options:

- Avoid friendly fire to other players unless hit by them first (Attackers are added to the Foe-List)
- Friend-List (These players never get attacked)
- Foe-List (These players are never exempt from the friendly fire feature)

**Comment by Darkhax** [comment]
Hello, thank you for submitting a feature request. The feature you are requesting is significantly out of scope for this mod though. I think you would have better luck using the vanilla teams feature or finding a dedicated team mod.
