### ISSUE TITLE
[Feature Request] Friendly Fire Tag for specific mobs, bind to Player OR Team Link

### ISSUE THREAD

**Issue by Sppcodetemp** [Darkhax-Minecraft/Friendly-Fire#59]
Would it be possible to add an item (usable nametag-like item or Wand) that grants Friendly Fire protections to any mob of choice? To account for entities that can still act friendly, or could use protection from individual players, but don’t have the Tameable attribute.

Could function as such:
>Player-A applies tag to Mob
>Player-A can no longer damage Mob unless using shift click to bypass protection
>Mob can *still be damaged by All Other Players*
>Like regular tamed mobs, Mob can only be linked to One Player At A Time
>For balance, a config toggle between craftable/noncraftable?

Or if that’s too much, a tag that links a Mob to a Team, then that Mob receives Friendly Fire protections from people on that team? (In vanilla this doesn’t work for mobs lol)
I can’t imagine these things are easy, not asking for everything 😂

Would this sort of feature be possible to implement, or ever considered? 
Thank you so much for your time. 🤍

**Comment by Darkhax** [comment]
Thank you for submitting a feature request. This sounds like a neat idea however this feature goes far beyond the scope of what this mod should do. It also sounds like something that can be easily abused, for example you could just claim strong mobs or bosses and use this mod to get around fighting them the proper way. 

The newest update for 1.20.4 adds team support which does cover some of what you want though.
