### ISSUE TITLE
[1.14] Whitelist for items that can attack pets

### ISSUE THREAD

**Issue by Noxalas** [Darkhax-Minecraft/Friendly-Fire#6]
Hello!

Playing on 1.14.4 with Respawnable Pets, but the item for respawn activation requires that I hit my wolf, which I can't do unless I uninstall Friendly Fire or disable "protectPetsFromOwner" in the config. 

I think a whitelist for items that let you hit pets would be a pretty good solution. c:

**Comment by Darkhax** [comment]
Sneaking should allow you to bypass the effects of this mod temporarily. New versions of the mod have some additional item tags to help with this.

`friendlyfire:bypass_pet` - lets the item hurt pets
`friendlyfire:bypass_all_protection` - Bypass all the basic protection offered by the mod.
