### ISSUE TITLE
Wolves are still trying to eat baby sheep

### ISSUE THREAD

**Issue by alinka62679** [Darkhax-Minecraft/Friendly-Fire#60]
Is there any way to fix this? Wild wolves hunt little sheep endlessly, that's why I can't tame them.

Minecraft 1.20.1

**Comment by Darkhax** [comment]
Thanks for letting me know about this. I've resolved this issue on 1.20.4 by changing the code to only protect child/baby mobs from attacks done by players. If that fix is okay I can backport it to older versions like 1.20.1.

**Comment by Darkhax** [comment]
Backported the changes to 1.20.1. File is currently being processed by CurseForge.
