### ISSUE TITLE
[QUESTION] Villagers, Iron Golems, Snow Golems, Modded Mobs

### ISSUE THREAD

**Issue by Gamemassa** [Darkhax-Minecraft/Friendly-Fire#61]
### Question

Two questions:

1. Does this mod prevent players from damaging Villagers, Iron Golems and Snow Golems?
2. Does this mod affect modded mobs?

And if no to either of the above, are they features that could be added in a future update?

**Comment by Darkhax** [comment]
1) Not by default as that is out of scope for what this mod does. You can add any mob to the `friendlyfire:player_protection` tag to protect them from players.
2) Yes it will work for pets added by mods as well. If you need anything beyond the base protections you can use the tags to add more. Tags also support modded mobs.

**Comment by Gamemassa** [comment]
> 1. Not by default as that is out of scope for what this mod does. You can add any mob to the `friendlyfire:player_protection` tag to protect them from players.
> 2. Yes it will work for pets added by mods as well. If you need anything beyond the base protections you can use the tags to add more. Tags also support modded mobs.

Oh, I see! Thanks so much for the quick reply. I assume adding mobs to tags is done through datapacks?

**Comment by Darkhax** [comment]
Yep, if you want to globally configure it across all worlds I would recommend using something like Open Loader to apply your datapack.

**Comment by Gamemassa** [comment]
> Yep, if you want to globally configure it across all worlds I would recommend using something like Open Loader to apply your datapack.

TBH I already have Paxi in my modpack, so Open Loader seems unnecessary.

**Comment by UmbralCosmos** [comment]
> 1. Not by default as that is out of scope for what this mod does. You can add any mob to the `friendlyfire:player_protection` tag to protect them from players.
> 2. Yes it will work for pets added by mods as well. If you need anything beyond the base protections you can use the tags to add more. Tags also support modded mobs.

I hope you don't mind my ignorance but how would I add the mobs to the `friendlyfire:player_protection` tag?
