### ISSUE TITLE
[BUG] EasyNPC and Friendly Fire conflict

### ISSUE THREAD

**Issue by RyoidenshiRyu** [Darkhax-Minecraft/Friendly-Fire#64]
### Minecraft Version

1.20.1

### Mod Version

18.0.6

### Mod Loader

Forge

### What environment are you running the mod in?

All

### Issue Description

I'm tried to fight NPC that I'm created, but since I counted as owner, I can attack NPC only when sneaking.
[I'm mentioned that issue to EasyNPC mod developer.](https://github.com/MarkusBordihn/BOs-Easy-NPC/issues/201)
There is a way to make datapack to bypass protection or another solution?

**Comment by Darkhax** [comment]
Hello, the author of EasyNPC is correct. You can add the NPC to the listed entity tags.

> However I don't see a friendlyfire:bypass_protection as entity tag or so.

I am not sure why they said this and the tag is defined and used in the code. 
- [example tag](https://github.com/Darkhax-Minecraft/Friendly-Fire/blob/1.20.1/common/src/main/resources/data/friendlyfire/tags/entity_types/bypassed_entity_types.json) - An empty example tag that is included with the mod. It shows you where the tag goes.
- [Code Usage](https://github.com/Darkhax-Minecraft/Friendly-Fire/blob/1.20.1/common/src/main/java/net/darkhax/friendlyfire/FriendlyFireCommon.java#L57) - This is where the tag is checked. If an entity is in this tag it is excluded from the protections offered by this mod.

If you have any further questions or concerns feel free to reply/ask here.
