### ISSUE TITLE
[QUESTION] Port to 1.21?

### ISSUE THREAD

**Issue by gustavomichelon** [Darkhax-Minecraft/Friendly-Fire#65]
### Question

Will there be a port to 1.21? If so when is it expected to release?

**Comment by Darkhax** [comment]
Hello, yes a 1.21 port is planned, no an ETA is not available. Here is a copy of my statement from Discord. 
![image](https://github.com/Darkhax-Minecraft/Friendly-Fire/assets/2250798/a0b6ffcb-86a4-420c-9409-acd04aa4e50f)
