### ISSUE TITLE
[QUESTION] How to add Mobs like Iron Golem to the Protection list (v.1.20.1)

### ISSUE THREAD

**Issue by BenDuckett95** [Darkhax-Minecraft/Friendly-Fire#68]
### Question

Hey, im using 1.20.1 version and trying to add FriendlyFire to CursedWalking Modpack to add Irongolems to the protected list. but i am not seeing a config file nor adding the example datapack given in curse forge is making the golems friendly. Do you have any advice on how to make this work? 

Thanks

**Comment by Darkhax** [comment]
Hello, 

Datapacks are a vanilla feature so we do not thoroughly document how to use them or offer technical support for the basics of creating and loading datapacks. 

The example pack linked on CurseForge adds villagers and the wandering trader to the `general_protection` tag which will make them immune to all forms of damage regardless of source. If you want to prevent players from hurting iron golems you can add the golem ID to the `player_protection` tag. 

The file would look something like this. If you still can't get this to work please lookup a tutorial on datapacks online.
**data/friendlyfire/tags/entity_types/player_protection.json**
```json
{
  "values": [
    "minecraft:iron_golem"
  ]
}
```
