### ISSUE TITLE
[1.16.3] Crash on world start - NPE - at net.darkhax.friendlyfire.FriendlyFire.preventAttack

### ISSUE THREAD

**Issue by ProsperCraft** [Darkhax-Minecraft/Friendly-Fire#7]
https://gist.github.com/ProsperCraft/7349913c590e2edb373ab389c63a5954

forge-1.16.3-34.1.1
FriendlyFire-1.16.3-5.0.1

**Comment by ProsperCraft** [comment]
[latest.log](https://github.com/Darkhax-Minecraft/Friendly-Fire/files/5300161/latest.log)

**Comment by Darkhax** [comment]
Thank you for reporting this, a new build will be live on CurseForge shortly. Let me know if it fixed your issue.

**Comment by ProsperCraft** [comment]
It doesn't seem to be crashing any longer, thank you.
