### ISSUE TITLE
[1.16.3] Server side requires 1.15.2

### ISSUE THREAD

**Issue by ProsperCraft** [Darkhax-Minecraft/Friendly-Fire#8]
Loading on a dedicated server-
FriendlyFire-1.16.3-5.0.2

[15:39:44] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Mod §efriendlyfire§r requires §6minecraft§r §o1.15.2§r
§7Currently, §6minecraft§r§7 is §o1.16.3

Crash log-
https://gist.github.com/ProsperCraft/85889f8fa3f5e058755150aa01ebd7dd

**Comment by Darkhax** [comment]
Thank you for reporting this issue. It should be fixed in the latest version.
