### ISSUE TITLE
Setting as Alpha on curseforge makes Twitch packs impossible

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/Friendly-Fire#9]
Hello, just a suggestion

Please do not post updates of your mods as Alpha if you want modpack developers to enable your mod.  Twitch ignores all Alpha version mods and refuses to install any marked as it.

**Comment by Darkhax** [comment]
Hello, you can actually get Twitch to pull in alpha files but it can be annoying. The current alpha file already has a lot of downloads from modpacks. I've marked the 1.16.3 version as a release, thanks for letting me know.
